{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "edt.fullname" . }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls: [{hosts: [{{ .Values.ingress.host | quote }}], secretName: {{ .Values.ingress.tlsSecretName }} }]
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend: {service: {name: edt-api, port: {number: 8080}}}
          - path: /
            pathType: Prefix
            backend: {service: {name: edt-web, port: {number: 3000}}}
{{- end }}
